name: World Workflow

on:
  workflow_dispatch:
    

jobs:
  hello_world:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create file with PowerShell
        run: |
          $filePath = "D:\DevOpsSoftware\GitHubActions\GitHubActions_Learning
          New-Item -Path "$filePath" -Name "Example.txt" -ItemType File -Force
          Set-Content -Path "$filePath\Example.txt" -Value "This is a Test"
          Get-Content -Path "$filePath\Example.txt"
        shell: pwsh  


      # - name: Delete file with PowerShell
      #   run: |
      #     $filePath = "D:\DevOpsSoftware\GitHubActions\GitHubActions_Learning\file.txt"  
      #         Remove-Item $filePath -Force
      #         Write-Host "File deleted successfully: $filePath"
      #     } else {
      #         Write-Host "File not found: $filePath"
      #     }
      #   shell: pwsh  

      