name: World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      